baseURL = 'https://beneath-our-footsteps-presentation.netlify.app/'
languageCode = 'en-gb'
languageDirection = 'ltr'  # Add this line
title = 'Compiler - Beneath Our Footsteps Slideshow'
theme = "ox-minimal"
enableGitInfo = true

# Add this line to enable future content
buildFuture = true

[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
